// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7lfJtme-rkfdNwpxZ3je2H_gF2O-fwvs',
    appId: '1:880183966639:web:4563390befdd203ea28d5a',
    messagingSenderId: '880183966639',
    projectId: 'tretanz-task',
    authDomain: 'tretanz-task.firebaseapp.com',
    storageBucket: 'tretanz-task.firebasestorage.app',
    measurementId: 'G-TVVP9QYKNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0lvQJEOs03UVv5nmbW993AquxZE7I7Bg',
    appId: '1:880183966639:android:35b714f8368de0d3a28d5a',
    messagingSenderId: '880183966639',
    projectId: 'tretanz-task',
    storageBucket: 'tretanz-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK_O5GjTvzdrbKeiOZ-Bbt2gVxc4N2X7M',
    appId: '1:880183966639:ios:b8d7298725269beaa28d5a',
    messagingSenderId: '880183966639',
    projectId: 'tretanz-task',
    storageBucket: 'tretanz-task.firebasestorage.app',
    iosBundleId: 'co.in.tretanz.tretanzTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK_O5GjTvzdrbKeiOZ-Bbt2gVxc4N2X7M',
    appId: '1:880183966639:ios:b8d7298725269beaa28d5a',
    messagingSenderId: '880183966639',
    projectId: 'tretanz-task',
    storageBucket: 'tretanz-task.firebasestorage.app',
    iosBundleId: 'co.in.tretanz.tretanzTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7lfJtme-rkfdNwpxZ3je2H_gF2O-fwvs',
    appId: '1:880183966639:web:a379f79efb9c3cc1a28d5a',
    messagingSenderId: '880183966639',
    projectId: 'tretanz-task',
    authDomain: 'tretanz-task.firebaseapp.com',
    storageBucket: 'tretanz-task.firebasestorage.app',
    measurementId: 'G-BCFM43Z49P',
  );
}
